# Generated by Django 4.2.3 on 2023-07-07 14:24

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpj', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
